<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>com.bluefate.eyetracker</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <RootNamespace>EyeTrackerWithOpenCV</RootNamespace>
    <AssemblyName>EyeTrackerWithOpenCV</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.7.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Camera.Camera2" Version="1.3.4.1" />
    <PackageReference Include="Xamarin.AndroidX.Camera.Lifecycle" Version="1.3.4.1" />
    <PackageReference Include="Xamarin.AndroidX.Camera.View" Version="1.3.4.1" />
    <PackageReference Include="Xamarin.Google.MLKit.FaceDetection" Version="3.0.0.4" />
  </ItemGroup>

  <ItemGroup>
    <AndroidResource Include="Resources\**\*" />
  </ItemGroup>
</Project>
